# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Placement_Cell_recruiter.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 748)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 350, 131, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/selected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(870, 10, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 110, 131, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Notifications.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 430, 131, 51))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 190, 131, 51))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 270, 131, 51))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Applications.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(170, 20, 801, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 90, 711, 241))
        self.textEdit_3.setObjectName("textEdit_3")
        self.toolButton_12 = QtWidgets.QToolButton(self.tab)
        self.toolButton_12.setGeometry(QtCore.QRect(40, 57, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_12.setFont(font)
        self.toolButton_12.setObjectName("toolButton_12")
        self.toolButton_13 = QtWidgets.QToolButton(self.tab)
        self.toolButton_13.setGeometry(QtCore.QRect(80, 57, 31, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.toolButton_13.setFont(font)
        self.toolButton_13.setObjectName("toolButton_13")
        self.toolButton_14 = QtWidgets.QToolButton(self.tab)
        self.toolButton_14.setGeometry(QtCore.QRect(120, 57, 31, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.toolButton_14.setFont(font)
        self.toolButton_14.setObjectName("toolButton_14")
        self.toolButton_15 = QtWidgets.QToolButton(self.tab)
        self.toolButton_15.setGeometry(QtCore.QRect(160, 57, 31, 31))
        self.toolButton_15.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/yellowhighlighter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_15.setIcon(icon6)
        self.toolButton_15.setObjectName("toolButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab)
        self.pushButton_16.setGeometry(QtCore.QRect(660, 350, 93, 28))
        self.pushButton_16.setObjectName("pushButton_16")
        self.toolButton_17 = QtWidgets.QToolButton(self.tab)
        self.toolButton_17.setGeometry(QtCore.QRect(720, 57, 31, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.toolButton_17.setFont(font)
        self.toolButton_17.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/attachment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_17.setIcon(icon7)
        self.toolButton_17.setObjectName("toolButton_17")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 771, 641))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(30, 40, 91, 16))
        self.label_33.setObjectName("label_33")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_23.setGeometry(QtCore.QRect(130, 40, 581, 22))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget.setGeometry(QtCore.QRect(10, 410, 731, 121))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(20, 550, 141, 16))
        self.label_34.setObjectName("label_34")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_24.setGeometry(QtCore.QRect(160, 550, 211, 22))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(400, 550, 31, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(30, 70, 91, 16))
        self.label_36.setObjectName("label_36")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_4.setGeometry(QtCore.QRect(130, 70, 581, 61))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_27.setGeometry(QtCore.QRect(100, 150, 121, 22))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox.setGeometry(QtCore.QRect(0, 140, 771, 261))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(240, 10, 51, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_30.setGeometry(QtCore.QRect(290, 10, 101, 22))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(140, 50, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(240, 50, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(340, 50, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_32.setGeometry(QtCore.QRect(430, 40, 311, 81))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton.setGeometry(QtCore.QRect(600, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(140, 80, 261, 91))
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(430, 10, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 51, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_28.setGeometry(QtCore.QRect(90, 180, 91, 22))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(430, 130, 51, 16))
        self.label_6.setObjectName("label_6")
        self.listView_2 = QtWidgets.QListView(self.groupBox)
        self.listView_2.setGeometry(QtCore.QRect(480, 130, 261, 41))
        self.listView_2.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView_2.setObjectName("listView_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(210, 180, 71, 16))
        self.label_7.setObjectName("label_7")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(290, 180, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(430, 180, 121, 16))
        self.label_8.setObjectName("label_8")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(630, 180, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_31.setGeometry(QtCore.QRect(440, 550, 301, 71))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.groupBox.raise_()
        self.label_33.raise_()
        self.lineEdit_23.raise_()
        self.tableWidget.raise_()
        self.label_34.raise_()
        self.lineEdit_24.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.textEdit_4.raise_()
        self.label_2.raise_()
        self.lineEdit_27.raise_()
        self.lineEdit_31.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(40, 90, 741, 471))
        self.tableWidget_2.setAutoFillBackground(False)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(30, 60, 741, 471))
        self.tableWidget_3.setAutoFillBackground(False)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(334, 20, 101, 20))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 30, 751, 231))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_18.setGeometry(QtCore.QRect(130, 50, 581, 22))
        self.lineEdit_18.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(30, 90, 91, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(30, 130, 91, 16))
        self.label_29.setObjectName("label_29")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_19.setGeometry(QtCore.QRect(130, 130, 581, 22))
        self.lineEdit_19.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_20.setGeometry(QtCore.QRect(130, 90, 581, 22))
        self.lineEdit_20.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_9.setGeometry(QtCore.QRect(610, 170, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 290, 751, 211))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_30 = QtWidgets.QLabel(self.groupBox_6)
        self.label_30.setGeometry(QtCore.QRect(20, 50, 101, 16))
        self.label_30.setObjectName("label_30")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_3.setGeometry(QtCore.QRect(130, 50, 241, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_31 = QtWidgets.QLabel(self.groupBox_6)
        self.label_31.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.label_31.setObjectName("label_31")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_21.setGeometry(QtCore.QRect(130, 100, 591, 22))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_10.setGeometry(QtCore.QRect(620, 160, 93, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Final Selections"))
        self.pushButton_6.setText(_translate("MainWindow", "Sign Out"))
        self.pushButton.setText(_translate("MainWindow", "Notifications"))
        self.pushButton_5.setText(_translate("MainWindow", "My Account"))
        self.pushButton_2.setText(_translate("MainWindow", "Company Info"))
        self.pushButton_3.setText(_translate("MainWindow", "Applications"))
        self.toolButton_12.setText(_translate("MainWindow", "B"))
        self.toolButton_13.setText(_translate("MainWindow", "I"))
        self.toolButton_14.setText(_translate("MainWindow", "U"))
        self.pushButton_16.setText(_translate("MainWindow", "Post"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Company Info"))
        self.label_33.setText(_translate("MainWindow", "Company Name"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Job Profile"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cut-Off"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stipend"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date of Visit"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Application Deadline"))
        self.label_34.setText(_translate("MainWindow", "Coordinator Respnsible"))
        self.label_35.setText(_translate("MainWindow", "Note"))
        self.label_36.setText(_translate("MainWindow", "About Company"))
        self.label_2.setText(_translate("MainWindow", "Job Profile"))
        self.label_9.setText(_translate("MainWindow", "Cut-Off"))
        self.label_4.setText(_translate("MainWindow", "Branches Eligible"))
        self.checkBox.setText(_translate("MainWindow", "B. Tech."))
        self.checkBox_2.setText(_translate("MainWindow", "M. Tech."))
        self.checkBox_3.setText(_translate("MainWindow", "MBA"))
        self.commandLinkButton.setText(_translate("MainWindow", "Add another Job"))
        self.label_3.setText(_translate("MainWindow", "Job Description"))
        self.label_5.setText(_translate("MainWindow", "Stipend"))
        self.label_6.setText(_translate("MainWindow", "Location"))
        self.label_7.setText(_translate("MainWindow", "Date of Visit"))
        self.label_8.setText(_translate("MainWindow", "Application Deadline"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Roll Number"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Application Status"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "View Resume"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Roll Number"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        self.label.setText(_translate("MainWindow", "Final Selections"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Change Password"))
        self.label_27.setText(_translate("MainWindow", "Old Password"))
        self.label_28.setText(_translate("MainWindow", "New Password"))
        self.label_29.setText(_translate("MainWindow", "New Password"))
        self.pushButton_9.setText(_translate("MainWindow", "Update"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Security Question"))
        self.label_30.setText(_translate("MainWindow", "Security Question"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "What was the name of my first pet?"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "What was my first school?"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "What is my mother\'s maiden name?"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Who is my favourite Hollywood star?"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "What is my brother\'s/sister\'s name?"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Who is my favourite sportsperson?"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "What is my best friend\'s name?"))
        self.label_31.setText(_translate("MainWindow", "Answer"))
        self.pushButton_10.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Page"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

